SELECT * FROM complaints;
select * FROM customers;
select * FROM deliverypartners;
select * FROM deliveryupdates;
select * FROM feedback;
select * FROM menuitems;
select * FROM orderdelivery;
select * FROM orderitems;
select * FROM orders;
select * FROM payment;
select * FROM restaurants;

-- 1. Display all customers who live in 'Delhi'
SELECT 
    *
FROM
    customers
WHERE
    city = 'delhi';

-- 2. Find the average rating of all restaurants in 'Mumbai'
SELECT 
    AVG(rating) AS avg_rating
FROM
    restaurants
WHERE
    city = 'mumbai';
    
    -- 3.LIST ALL CUSTOMERS WHO HAVE PLACED AT LEAST ONE ORDER.
    SELECT DISTINCT
o.customer_id, c.name, COUNT(o.order_id) AS total_orders
FROM

orders o

JOIN

customers c USING (customer_id)
GROUP BY customer_id;

 -- 4. DISPLAY THE TOTAL NUMBER OF ORDERS PLACED BY EACH CUSTOMER
SELECT 
    c.name AS customer_name,
    COUNT(o.order_id) AS total_orders
FROM Customers c
LEFT JOIN Orders o 
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name;

 -- 5.FIND THE TOTAL REVENUE GENERATED BY EACH RESTAURANT
SELECT 
    r.name AS restaurant_name,
    SUM(o.total_amount) AS total_revenue
FROM Restaurants r
JOIN Orders o 
    ON r.restaurant_id = o.restaurant_id
GROUP BY r.restaurant_id, r.name;

-- 6.FIND THE TOP 5 RESTAURANTS WITH THE HIGHEST AVERAGE RATING
SELECT 
    restaurant_id,
    name AS restaurant_name,
    ROUND(AVG(rating), 2) AS average_rating
FROM
    restaurants
WHERE
    rating IS NOT NULL
GROUP BY restaurant_id
ORDER BY AVG(rating) DESC
LIMIT 5;

-- 7.DISPLAY ALL CUSTOMERS WHO HAVE NEVER PLACED AN ORDER
SELECT 
    c.customer_id, c.name, COUNT(o.order_id) AS total_order
FROM
    customers c
        LEFT JOIN
    orders o USING (customer_id)
WHERE
    o.order_id IS NULL
GROUP BY c.customer_id;

-- 8.FIND THE NUMBER OF ORDERS PLACED BY EACH CUSTOMER IN 'MUMBAI'
SELECT
c.customer_id, c.name, COUNT(o.order_id) AS total_order
FROM

customers c

JOIN

orders o USING (customer_id)
WHERE

c.city = 'mumbai'
GROUP BY c.customer_id;

 -- 9.DISPLAY ALL ORDERS PLACED IN THE LAST 30 DAYS
 SELECT
    order_id, order_date
FROM
    orders
WHERE
    order_date >= DATE_SUB('2024-08-15',
        INTERVAL (30) DAY)
ORDER BY order_date DESC
LIMIT 30;

  -- 10..LIST ALL DELIVERY PARTNERS WHO HAVE COMPLETED MORE THAN 1 DELIVERY.
  SELECT 
    dp.partner_id,
    dp.name AS partner_name,
    COUNT(od.order_delivery_id) AS total_deliveries
FROM
    deliverypartners dp
        JOIN
    orderdelivery od USING (partner_id)
GROUP BY dp.partner_id
HAVING COUNT(od.order_id) > 1;

 -- 11.FIND THE CUSTOMERS WHO HAVE PLACED ORDERS ON EXACTLY THREE DIFFERENT DAYS.
 SELECT 
    c.customer_id,
    c.name,
    COUNT(DISTINCT (order_date)) AS total_delivery_days
FROM
    customers c
        JOIN
    orders o USING (customer_id)
GROUP BY customer_id
HAVING COUNT(DISTINCT (o.order_date)) = 3;
 
 -- 12.FIND THE DELIVERY PARTNER WHO HAS WORKED WITH THE MOST DIFFERENT CUSTOMERs.
 SELECT 
    dp.partner_id,
    dp.name,
    COUNT(DISTINCT o.order_id) AS total_different_customer
FROM
    deliverypartners dp
        JOIN
    orderdelivery od USING (partner_id)
        JOIN
    orders o USING (order_id)
GROUP BY partner_id
ORDER BY COUNT(DISTINCT o.order_id) DESC
LIMIT 1;

 -- 13.IDENTIFY CUSTOMERS WHO HAVE THE SAME CITY AND HAVE PLACED ORDERS AT THE SAME RESTAURANTS, BUT ON DIFFERENT DATES.
 SELECT DISTINCT
    c1.name AS customer_1,
    c2.name AS customer_2,
    c1.city,
    r.name AS restaurant_name,
    DATE(o1.order_date) AS customer_1_order_date,
    DATE(o2.order_date) AS customer_2_order_date
FROM
    Customers c1
        JOIN
    Orders o1 ON c1.customer_id = o1.customer_id
        JOIN
    Customers c2 ON c1.city = c2.city
        AND c1.customer_id < c2.customer_id
        JOIN
    Orders o2 ON c2.customer_id = o2.customer_id
        AND o1.restaurant_id = o2.restaurant_id
        AND DATE(o1.order_date) <> DATE(o2.order_date)
        JOIN
    Restaurants r ON o1.restaurant_id = r.restaurant_id;
